package com.cidic.sdx.dggl.model;
// Generated 2017-2-21 14:08:23 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Feedback generated by hbm2java
 */
@Entity
@Table(name = "feedback", catalog = "sdx_cloud")
public class Feedback implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Matchlist matchlist;
	private int likeId;

	public Feedback() {
	}

	public Feedback(Matchlist matchlist, int likeId) {
		this.matchlist = matchlist;
		this.likeId = likeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matchlistId")
	public Matchlist getMatchlist() {
		return this.matchlist;
	}

	public void setMatchlist(Matchlist matchlist) {
		this.matchlist = matchlist;
	}

	@Column(name = "likeId")
	public int getLikeId() {
		return this.likeId;
	}

	public void setLikeId(int likeId) {
		this.likeId = likeId;
	}

}
