package com.cidic.sdx.dggl.model;
// Generated 2017-3-14 9:45:44 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Vipuser generated by hbm2java
 */
@Entity
@Table(name = "vipuser", catalog = "sdx_cloud", uniqueConstraints = @UniqueConstraint(columnNames = "guideId"))
@DynamicInsert(true)
@DynamicUpdate(true)
public class Vipuser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private String cardnumber;
	private String vipname;
	private String shopname;
	private byte gender;
	private Date birthday;
	private String phonenumber;
	private Short integral;  //积分
	private Short consumenumber; //消费次数
	private BigDecimal consumesum; //累计消费金额
	private int valid; //用户有效标志
	private char rank; //
	
	public Vipuser() {
	}

	public Vipuser(User user, String cardnumber, String vipname, byte gender) {
		this.user = user;
		this.cardnumber = cardnumber;
		this.vipname = vipname;
		this.gender = gender;
	}

	public Vipuser(User user, String cardnumber, String vipname, String shopname, byte gender, Date birthday,char rank,
			String phonenumber, Short integral, Short consumenumber, BigDecimal consumesum) {
		this.user = user;
		this.cardnumber = cardnumber;
		this.vipname = vipname;
		this.shopname = shopname;
		this.gender = gender;
		this.birthday = birthday;
		this.phonenumber = phonenumber;
		this.integral = integral;
		this.consumenumber = consumenumber;
		this.consumesum = consumesum;
		this.rank = rank;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "guideId", unique = true, nullable = false)
	@JsonIgnore
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "cardnumber", nullable = false, length = 15)
	public String getCardnumber() {
		return this.cardnumber;
	}

	public void setCardnumber(String cardnumber) {
		this.cardnumber = cardnumber;
	}

	@Column(name = "vipname", nullable = false, length = 20)
	public String getVipname() {
		return this.vipname;
	}

	public void setVipname(String vipname) {
		this.vipname = vipname;
	}

	@Column(name = "shopname", length = 40)
	public String getShopname() {
		return this.shopname;
	}

	public void setShopname(String shopname) {
		this.shopname = shopname;
	}

	@Column(name = "gender", nullable = false)
	public byte getGender() {
		return this.gender;
	}

	public void setGender(byte gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "phonenumber", length = 11)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "integral")
	public Short getIntegral() {
		return this.integral;
	}

	public void setIntegral(Short integral) {
		this.integral = integral;
	}

	@Column(name = "consumenumber")
	public Short getConsumenumber() {
		return this.consumenumber;
	}

	public void setConsumenumber(Short consumenumber) {
		this.consumenumber = consumenumber;
	}

	@Column(name = "consumesum", precision = 10)
	public BigDecimal getConsumesum() {
		return this.consumesum;
	}

	public void setConsumesum(BigDecimal consumesum) {
		this.consumesum = consumesum;
	}

	@Column(name = "valid")
	public int getValid() {
		return valid;
	}

	public void setValid(int valid) {
		this.valid = valid;
	}
	
	@Column(name = "rank", nullable = false, length = 1)
	public char getRank() {
		return this.rank;
	}

	public void setRank(char rank) {
		this.rank = rank;
	}
}
